name: portfolio-v1
services:
  portfolio:
    build: .
    container_name: portfolio-v1
    image: portfolio-v1
    ports:
      - "5173:5173"  # Vite's default port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true